### ISSUE TITLE
about forked version

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#10]
i just discovered a fork of your engine here: https://github.com/FireFather/pawn .. i know this is legal, but can you tell me how links to forks are arranged on GitHub ? I mean you could have a link in your README to such forks, the fork page DOES show a link to its original!

this version has your name as author .. and it has no version number either .. so how can we know the creator of the (forked) engine ? Btw. that GitHub page doesn't have an `Issues` menu item, it's disabled, so i can not communicate with this coder, can i ? I want to found out why he (she) forked your Pawn .. 'cause it's an awesome engine ?

**Comment by ruicoelhopedro** [comment]
This is not an issue, afaik, forks are normal as long as they remain compliant with the original licence (GPL-3 in the case of pawn). GitHub keeps track of the forks in both repos.

**Comment by tissatussa** [comment]
> GitHub keeps track of the forks in both repos

thanks, i didn't know that .. now i have to discover where i can see these tracks in the menus .. i'm not familiar with the GitHub setup.
