### ISSUE TITLE
PSQT .dat file has pawn structure patterns ?

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#14]
i was wondering .. your pawn is the only engine i know which has a (.dat) file concerning Piece-SQuare-Tables .. and i don't remember previous pawn versions had such .. i guess it's part of a next version.

the .dat file is no plain text - it will contain those tables .. or does pawn have some NN now ? Or pawn structure patterns and such ?

you might not want to fully tell us your code ideas, i know ..

**Comment by ruicoelhopedro** [comment]
That file contains all the weights for the recent dynamic PSQ tables introduced in #12. Since they are quite a lot of values, I have packed them into that binary file (which has the .dat extension, but could have been something else). You can interpret them as some sort of NN, yes.


> you might not want to fully tell us your code ideas, i know ..

If that was the case, this project wouldn't be open source ;)

**Comment by tissatussa** [comment]
>  You can interpret them as some sort of NN, yes.

nice! are (only) self play games involved ?

**Comment by ruicoelhopedro** [comment]
> nice! are (only) self play games involved ?

Yes, the training data is generated in self-play at a fixed shallow depth with some random moves to introduce diversity.

**Comment by AlexBrunetti** [comment]
> You can interpret them as some sort of NN, yes.

This is an indexed table, as I can understand from the code; how can you call it a sort of NN?

Alex

**Comment by ruicoelhopedro** [comment]
In the sense that it contains the weights for a trained data-driven model used during evaluation. It's not an NN, but it is stored in a similar fashion as one would be.
