### ISSUE TITLE
contempt is agressive ?

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#3]
the current Pawn version plays agressive !
it gladly sacrifices pawns and pieces for attack and complications, i like that !
i see Pawn does not go into great depth quickly, but often such sharp continuations require precise calculations ?

i did games in CuteChess against several engines, with 8 minutes per game : 4 games see [Pawn_4_agressive_games.zip](https://github.com/ruicoelhopedro/pawn/files/8147454/Pawn_4_agressive_games.zip)

---

sac1 : **DeepBrutePos v2.4 (rating?) - Pawn**
position below

![sac1](https://user-images.githubusercontent.com/1109281/155858095-25359dd0-bb86-42a9-9b4c-8b2979ca0713.png)

15...Bxe3 ! and Pawn won.
FEN after 15.e3 : r2q1rk1/1b1n1ppp/pb6/1p6/P5n1/1QN1PN2/1PP2PPP/3RKB1R b K - 0 15

---

sac2 : **CaffeinatedPawn f54f165 (rating?) - Pawn**
position below

![sac2](https://user-images.githubusercontent.com/1109281/155858100-a7b08584-0dfb-4feb-afe1-1a228ac4523d.png)

Pawn plays 3...e6! after 11 sec : the Icelandic gambit, agressive! I guess Pawn does not have an internal openingbook .. this gambit is sharp with precise deep variations .. Pawn won the game in great agressive style ! (but the strength of CaffeinatedPawn is unknown to me ..)
FEN after 3.c4 : rnbqkb1r/ppp1pppp/5n2/3P4/2P5/8/PP1P1PPP/RNBQKBNR b KQkq - 0 3
FEN after 10.d5 : 2kr3r/ppp1qppp/2n1bn2/3P4/2P5/5N2/PP2QPPP/RN2KB1R b KQ - 0 10 

---

sac3 : **Eden v0.0.13 (1405) - Pawn**
position below

![sac3](https://user-images.githubusercontent.com/1109281/155858105-2ed4e8d9-c6b0-4121-8c7e-c04b9f00531f.png)

Pawn let White capture a pawn by Qxb7 and now Pawn plays Nd4! and wins quickly with a nice mate attack. Agressive !
FEN after 9.Qxb7 : r3kb1r/1Qp2ppp/p1n1pn2/3q4/6b1/4PN2/PP1PBPPP/RNB2RK1 b kq - 0 9

---

sac4 : **Flux v2.2.2 (2357) - Pawn**
position below

![sac4](https://user-images.githubusercontent.com/1109281/155858109-f01b50be-56c5-4188-a644-5e66d5ccf630.png)

Pawn has expanded the pawns on the Kingside while having castled (!) and now Pawn even plays 16...b5! , leaving no shelter for the King with still many pieces on the board .. however, White can hardly move and Pawn wins nicely. Agressive !  And Flux is rather strong!  (however, Flux also can win..)
FEN after 16.Qb3 : r3k2r/1p2qp2/p1p2n1p/2bpn1p1/8/1QN1P2P/PPP1BPP1/R1BR2K1 b kq - 0 16

---

so, Pawn sometimes loses with this agressive strategy : its 'contempt' seems high, and stronger engines resist this 'force' ..?!

here more recent Pawn games (while testing several found java .jar engines) : [Pawn_games1.zip](https://github.com/ruicoelhopedro/pawn/files/8147453/Pawn_games1.zip)
times per move are included by CuteChess.

---
_YOUR VIDEO BONUS TODAY
Chess Fuga
https://www.bitchute.com/video/g83R4hXKoMe0/_

**Comment by ruicoelhopedro** [comment]
Thank you for the feedback and the games! Glad the playstyle is exciting :)

Pawn loves mobility and space, and it will gladly sacrifice material to create attacks and complications. But in general, it is too optimistic and ends up blundering a lot (partially because of the lack of depth). It does not feature contempt (yet).
