### ISSUE TITLE
dynamic PST

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#4]
recently i let Pawn play against many (weak) engines, just to see how it plays (agressive!) and to determine its rating; at this moment i guess it's around 2300 .. sometimes Pawn draws or even wins a game against a much stronger engine !?

you seem to have knowledge about the general search & pruning and 'LMR research ratio' etc .. i'm not very familiar with all those concepts, but i can imagine and read some texts about it .. but i was wondering : i guess you're using a PST(s) ? As i understand, these hold some basic reference values for all squares regarding the pieces and their (optimal) movement, and these PSTs are fixed .. what if certain aspects of the position determine a 'custum PST' to use ? Such determining process might even be recursive ?

this is my idea in short, i can elaborate.
just thinking out of the box :-)

![King_move](https://user-images.githubusercontent.com/1109281/156087356-907edf86-8a8b-41d2-8c2a-cf78a40dbeb2.png)

**Comment by ruicoelhopedro** [comment]
The PSQT are already somewhat "dynamic", in the sense that we have both middlegame and endgame tables, and we are constantly interpolating between them. You can check this in pawn [here](https://github.com/ruicoelhopedro/pawn/blob/main/src/PieceSquareTables.hpp).
