### ISSUE TITLE
test for Pawn : the Scotch Gambit

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#6]
For a long time i was not able to play chess at my club, due to the CV19 restrictions .. however, last Friday i played some games there and i spoke with friends, etc. .. we discussed a typical agressive opening, the Scotch Gambit, which has a good reputation for attacking players : Black should know the lines, otherwise Black will lose quickly .. so, i analysed this position with several engines :

![Pawn_xd4-or-xe4](https://user-images.githubusercontent.com/1109281/156912300-69eaaf1f-3d73-4a64-9808-bf60d4b3d354.png)

r1b1kb1r/ppp2ppp/2n5/q7/3pn3/2N2N2/PPP2PPP/R1BQR1K1 w kq - 0 9

this position is the result of the following Scotch Gambit moves :
_1.e4 e5 2.Nf3 Nc6 3.d4 exd4 4.Bc4 Nf6 5.O-O Nxe4 6.Re1 d5 7.Bxd5 Qxd5 8.Nc3 Qa5 *_

White sacrificed a piece and a pawn, but has a strong attack .. in this position only 1 move is best, according to SF 14 and many other strong engines : 9. Nxe4

You see the analysis in SCID of SF 14 NNUE and Pawn : the move 9. Nxe4 is clearly best, after letting SF 14 run for some time .. however, even after a long thinking time Pawn finds Nxd4 best move !?  This way Pawn sacrifices more material, but this is certainly NOT the right approach .. i tested many other engines in this position, and ALL (!) do NOT find Nxd4 best move, Pawn is the only one ..

i just stumbled upon this position, it may suit you to develop Pawn and make it play more sane ?

**Comment by ruicoelhopedro** [comment]
Thanks for the report, I'll take a look at it. Once again, probably an evaluation issue where pawn finds compensation where there is none.

**Comment by tissatussa** [comment]
yes, but i like Pawn's style !
recently i came upon "Chess System Tal", see https://www.chessprogramming.org/Chess_System_Tal
one of the links on that page is the forum entry "what is known about CSTal's inner workings?", see http://www.talkchess.com/forum3/viewtopic.php?t=53174
this may be an interesting read for you, concerning 'attractiveness of a playing style' ..
