### ISSUE TITLE
Pawn thinks while only 1 move possible

### ISSUE THREAD

**Issue by tissatussa** [ruicoelhopedro/pawn#7]
Often Pawn is thinking for many seconds while only 1 move is possible .. i think you should fix this, with instant benefit ..

**Comment by ruicoelhopedro** [comment]
This needs to be tested. Even when only one move is possible, time is not wasted as we are filling the hash table. I'm down to reducing the allocated search time if it proves beneficial.

**Comment by tissatussa** [comment]
OK.  I'm certain you're aware of this issue .. i don't know how to implement such thing in code, but i guess all valid moves in a position are known before starting any eval, so when the movelist has only one move, why not instantly play it ?
